# Symbols

TEST_SYMBOL_DIV = 'ZIM' # Dividends but no splits
TEST_SYMBOL_DIV_QUOTE_EXCHANGE = 'n'
TEST_SYMBOL_DIV_QUOTE_EXCHANGE_NAME = 'NYSE'
TEST_SYMBOL_DIVSPLIT = 'AAPL' # Dividends and splits
TEST_SYMBOL_DIVSPLIT_QUOTE_EXCHANGE = 'q'
TEST_SYMBOL_DIVSPLIT_QUOTE_EXCHANGE_NAME = 'NASD'
TEST_SYMBOL_SPLIT = 'AMZN' # Splits but no dividends
TEST_SYMBOL_SPLIT_QUOTE_EXCHANGE = 'q'
TEST_SYMBOL_SPLIT_QUOTE_EXCHANGE_NAME = 'NASD'
TEST_SYMBOL_NODIVSPLIT = 'TWLO' # No splits or dividends
TEST_SYMBOL_NODIVSPLIT_QUOTE_EXCHANGE = 'n'
TEST_SYMBOL_NODIVSPLIT_QUOTE_EXCHANGE_NAME = 'NYSE'
TEST_SYMBOL_FAKE = 'BADSYMBOL'
TEST_SYMBOL_FAKE_TWO = 'FOOBAR'

SYMBOL = TEST_SYMBOL_DIVSPLIT

# Signals and positioning

BUY = 'Buy'
SELL = 'Sell'

# Quantities (defaults)

STOP_LOSS = .98 # Two percent stop loss on buy/short
TEST_PURCHASE_SIZE = 100 # Shares

# Miscellaneous

# These settings are temporary
REGULAR_MARKET_OPEN_TIME = '09:30:00'
REGULAR_MARKET_CLOSE_TIME = '16:00:00'
