# Symbols

TEST_SYMBOL_ONE = 'ZIM'
TEST_SYMBOL_ONE_EXCHANGE = 'nyse'
TEST_SYMBOL_TWO = 'AAPL'
TEST_SYMBOL_TWO_EXCHANGE = 'nasdaq'
TEST_SYMBOL_FAKE = 'BADSYMBOL'
TEST_SYMBOL_FAKE_TWO = 'FOOBAR'

SYMBOL = TEST_SYMBOL_ONE

# Signals and positioning

BUY = 'Buy'
SELL = 'Sell'

# Quantities (defaults)

TEST_PURCHASE_SIZE = 100 # Shares
