# Symbols

TEST_SYMBOL_ONE = 'ZIM'
TEST_SYMBOL_ONE_QUOTE_EXCHANGE = 'n'
TEST_SYMBOL_ONE_QUOTE_EXCHANGE_NAME = 'NYSE'
TEST_SYMBOL_TWO = 'AAPL'
TEST_SYMBOL_TWO_QUOTE_EXCHANGE = 'q'
TEST_SYMBOL_TWO_QUOTE_EXCHANGE_NAME = 'NASD'
TEST_SYMBOL_FAKE = 'BADSYMBOL'
TEST_SYMBOL_FAKE_TWO = 'FOOBAR'

SYMBOL = TEST_SYMBOL_ONE

# Signals and positioning

BUY = 'Buy'
SELL = 'Sell'

# Quantities (defaults)

TEST_PURCHASE_SIZE = 100 # Shares
