" Core settings

set autoindent      " Continue indentation
set encoding=utf-8  " Universal encoding
set expandtab       " Expand tabstop to spaces
set fileformat=unix " Working on UNIX
set termguicolors   " Enable 24-bit RGB color
syntax on           " Syntax highlighting

" NOTE: Check available colors within vim
" :so $VIMRUNTIME/syntax/colortest.vim

" vim-pathogen

call pathogen#infect()
call pathogen#helptags()
filetype plugin indent on

" NERDTree

" Open NERDTree window on opening Vim and go to editing window
autocmd VimEnter * NERDTree | wincmd p
" Refresh the current folder if there are any changes
autocmd BufEnter NERD_tree_* | execute 'normal R'
au CursorHold * if exists("t:NerdTreeBufName") | call <SNR>15_refreshRoot() | endif
" Reload the window if directory is changed
augroup DIRCHANGE
    au!
    autocmd DirChanged global :NERDTreeCWD
augroup END
" Close NERDTree automatically if it is the only window open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1

" python-mode

" Set 80-column width line to dark blue
highlight ColorColumn guibg=darkblue
" Set line number gutter width to five spaces
set numberwidth=5
" Change line numbers to red
highlight LineNr term=bold cterm=NONE ctermfg=Red ctermbg=NONE gui=NONE guifg=Red guibg=NONE

" ale

" Only use ale for javascript
let b:ale_linters = ['eslint']
" Configure prettier code formatter; F6 to prettify
let g:ale_fixers = {'javascript': ['eslint']}
nmap <F6> <Plug>(ale_fix)
" Disable highlighting
let g:ale_set_highlights = 0
" Customize errors and warnings
let g:ale_echo_msg_error_str = 'ERROR'
let g:ale_echo_msg_warning_str = 'WARNING'
let g:ale_echo_msg_format = '%severity% [%code%] %s [%linter%]'
" Last (l) and next (n) errors:
nmap <silent> <C-l> <Plug>(ale_previous_wrap)
nmap <silent> <C-n> <Plug>(ale_next_wrap)

" coc.nvim

" Autocomplete menu colors
highlight Pmenu term=bold cterm=None ctermfg=lightblue ctermbg=NONE gui=NONE guifg=red guibg=NONE
" Enter key selects autocomplete choice
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

" F4 to clear search

nnoremap <F4> :nohl<CR><C-l>:echo "Search Cleared"<CR>

" F3 to execute python script

autocmd FileType python nnoremap <buffer> <F5> :w<cr>:exec '!clear'<cr>:exec '!python3' shellescape(expand('%:p'), 1)<cr>

" Core settings for major file types

autocmd FileType bash setlocal shiftwidth=4 tabstop=4
autocmd FileType css setlocal shiftwidth=2 tabstop=2 
autocmd FileType html setlocal shiftwidth=2 tabstop=2
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2
autocmd FileType perl setlocal shiftwidth=4 tabstop=4
