#!/bin/sh

django_conf_file=/etc/nginx/conf.d/django.conf
django_dev_server_port=8000

# Start the Django development server if currently configured to run
status="0"
/usr/bin/grep $django_dev_server_port $django_conf_file 2>&1 > /dev/null
status=$?
if [ "$status" -eq "0" ]; then
    /usr/local/bin/startserver.py
fi
